/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives': RouteRecordInfo<
      '/archives',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/[name]': RouteRecordInfo<
      '/categories/[name]',
      '/categories/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/friends': RouteRecordInfo<
      '/friends',
      '/friends',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/[slug]': RouteRecordInfo<
      '/posts/[slug]',
      '/posts/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/[name]': RouteRecordInfo<
      '/tags/[name]',
      '/tags/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/archives.vue': {
      routes:
        | '/archives'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/categories/index.vue': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/categories/[name].vue': {
      routes:
        | '/categories/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/friends.vue': {
      routes:
        | '/friends'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/posts/[slug].vue': {
      routes:
        | '/posts/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'src/pages/tags/index.vue': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tags/[name].vue': {
      routes:
        | '/tags/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
