/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementCard: typeof import('./../components/sidebar/AnnouncementCard.vue')['default']
    AppFooter: typeof import('./../components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    AppIcon: typeof import('./../components/common/AppIcon.vue')['default']
    ArchiveTimeline: typeof import('./../components/blog/ArchiveTimeline.vue')['default']
    AuthorCard: typeof import('./../components/sidebar/AuthorCard.vue')['default']
    BackToTop: typeof import('./../components/common/BackToTop.vue')['default']
    FriendCard: typeof import('./../components/friends/FriendCard.vue')['default']
    HomeBanner: typeof import('./../components/home/HomeBanner.vue')['default']
    ImageLightbox: typeof import('./../components/post/ImageLightbox.vue')['default']
    PostCard: typeof import('./../components/blog/PostCard.vue')['default']
    PostCopyright: typeof import('./../components/post/PostCopyright.vue')['default']
    PostLinkList: typeof import('./../components/blog/PostLinkList.vue')['default']
    PostNav: typeof import('./../components/post/PostNav.vue')['default']
    PostPagination: typeof import('./../components/blog/PostPagination.vue')['default']
    PostSkeleton: typeof import('./../components/common/PostSkeleton.vue')['default']
    PostToc: typeof import('./../components/post/PostToc.vue')['default']
    ReadingProgress: typeof import('./../components/common/ReadingProgress.vue')['default']
    RecentPostsCard: typeof import('./../components/sidebar/RecentPostsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./../components/search/SearchDialog.vue')['default']
    SearchResultItem: typeof import('./../components/search/SearchResultItem.vue')['default']
    SidebarCard: typeof import('./../components/sidebar/SidebarCard.vue')['default']
    TagCloud: typeof import('./../components/sidebar/TagCloud.vue')['default']
    TypewriterText: typeof import('./../components/home/TypewriterText.vue')['default']
  }
}
