/** 自研内联图标集的名字（没有引图标库：全站只用这几个，内联 SVG 更省） */
export type IconName =
  | 'sun'
  | 'moon'
  | 'menu'
  | 'close'
  | 'search'
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'calendar'
  | 'clock'
  | 'folder'
  | 'tag'
  | 'bell'
  | 'github'
  | 'mail'
  | 'rss'
  | 'link';
